apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: client
  template:
    metadata:
      labels:
        component: client
    spec:
      containers:
        - name: client
          image: haadiyasajid/final-exam:client
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: client-service
spec:
  selector:
    component: client
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: NodePort