apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
      - name: mongo
        image: mongo
        volumeMounts:
        - name: mongo-storage
          mountPath: /data/db
        ports:
        - containerPort: 27017
      - name: auth
        image: haadiyasajid/final-exam:auth
        ports:
        - containerPort: 4000
      - name: classrooms 
        image: haadiyasajid/final-exam:classroom
        ports:
        - containerPort: 4001
      - name: event-bus
        image: haadiyasajid/final-exam:event-bus
        ports:
        - containerPort: 4009 
      - name: post
        image: haadiyasajid/final-exam:post
        ports:
        - containerPort: 4002
      
      volumes:
      - name: mongo-storage
        persistentVolumeClaim:
          claimName: mongo-pvc
